const FETCH_DATA = 'FETCH_DATA';
const SET_EXCHANGE_RATES = 'SET_EXCHANGE_RATES';
const CHANGE_CURRENCY_FROM = 'CHANGE_CURRENCY_FROM';
const CHANGE_CURRENCY_TO = 'CHANGE_CURRENCY_TO';
const SET_AMOUNT = 'SET_AMOUNT';
const UPDATE_WALLET = 'UPDATE_WALLET';
const UPDATE_HISTORY = 'UPDATE_HISTORY';

export default {
  FETCH_DATA,
  CHANGE_CURRENCY_FROM,
  SET_EXCHANGE_RATES,
  CHANGE_CURRENCY_TO,
  SET_AMOUNT,
  UPDATE_WALLET,
  UPDATE_HISTORY,
};
