const SET_EXCHANGE_RATES = 'SET_EXCHANGE_RATES';
const CHANGE_CURRENCY_FROM = 'CHANGE_CURRENCY_FROM';
const CHANGE_CURRENCY_TO = 'CHANGE_CURRENCY_TO';
const UPDATE_WALLET = 'UPDATE_WALLET';
const UPDATE_HISTORY = 'UPDATE_HISTORY';

export default {
  CHANGE_CURRENCY_FROM,
  SET_EXCHANGE_RATES,
  CHANGE_CURRENCY_TO,
  UPDATE_WALLET,
  UPDATE_HISTORY,
};
